/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covidjabma.Ui;
import covidjabma.Controller;
import covidjabma.Ui.SignUp;
import covidjabma.Ui.Forgotpassword;
import covidjabma.Ui.Home;
import covidjabma.Ui.Manager;
import covidjabma.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Manager
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
      
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        passwordtxt = new javax.swing.JPasswordField();
        nationalidtxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        signinlbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        signuplbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(74, 31, 40));
        jPanel2.setAutoscrolls(true);

        jPanel6.setBackground(new java.awt.Color(74, 31, 41));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(186, 79, 84));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        passwordtxt.setBackground(new java.awt.Color(186, 79, 84));
        passwordtxt.setForeground(new java.awt.Color(204, 204, 204));
        passwordtxt.setText("Password");
        passwordtxt.setBorder(null);
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 190;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 40, 0, 88);
        jPanel3.add(passwordtxt, gridBagConstraints);

        nationalidtxt.setBackground(new java.awt.Color(186, 79, 84));
        nationalidtxt.setForeground(new java.awt.Color(204, 204, 204));
        nationalidtxt.setText("UserName");
        nationalidtxt.setBorder(null);
        nationalidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalidtxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 190;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 40, 0, 88);
        jPanel3.add(nationalidtxt, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 189;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 40, 0, 88);
        jPanel3.add(jSeparator1, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 189;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 88);
        jPanel3.add(jSeparator2, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(186, 79, 84));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        signinlbl.setBackground(new java.awt.Color(255, 255, 255));
        signinlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signinlbl.setForeground(new java.awt.Color(255, 255, 255));
        signinlbl.setText("     Sign in");
        signinlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinlblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signinlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signinlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 40, 0, 0);
        jPanel3.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(186, 79, 84));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel5.setForeground(new java.awt.Color(204, 204, 204));

        signuplbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signuplbl.setForeground(new java.awt.Color(255, 255, 255));
        signuplbl.setText("     Sign Up");
        signuplbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signuplblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signuplbl, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signuplbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 88);
        jPanel3.add(jPanel5, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Forgot Password ?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 60, 87, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void nationalidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalidtxtActionPerformed

    private void signuplblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signuplblMouseClicked
         SignUp signUp=new SignUp();
         signUp.show();
         this.hide();
    }//GEN-LAST:event_signuplblMouseClicked

    private void signinlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinlblMouseClicked
       
        try {
            Controller col=new Controller();
            String data;
            
            data=col.login(this.nationalidtxt.getText(), this.passwordtxt.getText());
            
            if(!data.equals("UnKnown")){
               
                if(data.split("\t").length<3){
                    return;
                }
                if(data.split("\t")[3].equalsIgnoreCase("1"))
                {
                 //EnterPrise1   
                    EntPrise enter=new EntPrise();
                    enter.setName(data.split("\t")[1]);
                    enter.setId("1");
                    enter.show();
                     this.hide();
                }
                if(data.split("\t")[3].equalsIgnoreCase("2"))
                {
                    //EnterPrise2
                    EntPrise enter=new EntPrise();
                    enter.setName(data.split("\t")[1]);
                    enter.setId("2");
                    enter.show();
                     this.hide();
                }
                if(data.split("\t")[3].equalsIgnoreCase("3"))
                {//EnterPrise3
                    EntPrise enter=new EntPrise();
                    enter.setName(data.split("\t")[1]);
                    enter.setId("3");
                    enter.show();
                     this.hide();
                }
                 if(data.split("\t")[3].equalsIgnoreCase("4"))
                {
                        //EnterPrise4
                    EntPrise enter=new EntPrise();
                    enter.setName(data.split("\t")[1]);
                    enter.setId("4");
                    enter.show();
                     this.hide();
                }
                if(data.split("\t")[3].equalsIgnoreCase("5"))
                {
                    /// org 1
                     Organization org=new Organization();
                    org.SetId("3");
                    org.setName(data.split("\t")[1]);
                    org.show();
                     this.hide();
                }
                if(data.split("\t")[3].equalsIgnoreCase("6"))
                {
                        /// org 2
                     Organization org=new Organization();
                    org.SetId("2");
                    org.setName(data.split("\t")[1]);
                    org.show();
                     this.hide();
                    
                }
                 if(data.split("\t")[3].equalsIgnoreCase("7"))
                {
                        /// org 3
                     Organization org=new Organization();
                    org.SetId("3");
                    org.setName(data.split("\t")[1]);
                    org.show();
                    this.hide();
                }
                if(data.split("\t")[3].equalsIgnoreCase("8"))
                {
                        /// org 4
                     Organization org=new Organization();
                    org.SetId("4");
                    org.setName(data.split("\t")[1]);
                    org.show();
                     this.hide();
                }
                if(data.split("\t")[3].equalsIgnoreCase("9"))
                {
                        /// org 5
                     Organization org=new Organization();
                    org.SetId("5");
                    org.setName(data.split("\t")[1]);
                    org.show();
                     this.hide();
                }
                  if(data.split("\t")[3].equalsIgnoreCase("10"))
                {
                    /// org 6
                    Organization org=new Organization();
                    org.SetId("6");
                    org.setName(data.split("\t")[1]);
                    org.show();
                     this.hide();
                    
                    
                }
                if(data.split("\t")[3].equalsIgnoreCase("11"))
                {
                    Manager admin=new Manager();
                    admin.setId(data.split("\t")[0]);
                    admin.setName(data.split("\t")[1]);
                    admin.setusername(data.split("\t")[2]);
                    admin.show();
                    this.hide();
                }
                if(data.split("\t")[3].equalsIgnoreCase("12"))
                {//the derivery man
                    
                  DeriveryMan del=new DeriveryMan();
                  del.setName(data.split("\t")[1]);
                  del.show();
                  this.hide();
                  
                }
                if(data.split("\t")[3].equalsIgnoreCase("13"))
                {
                    //client
                    Home home=new Home();
                    home.setId(data.split("\t")[0]);
                    home.setName(data.split("\t")[1]);
                    home.setusername(data.split("\t")[2]);
                    home.show();
                    this.hide();
                }
                if(data.split("\t")[3].equalsIgnoreCase("14"))
                {
                    //admin
                    Admin admin =new Admin();
                    admin.setName(data.split("\t")[1]);
                    admin.show();
                    this.hide();
                   
                    
                }
               
            
                
            }
            else{
                this.nationalidtxt.setText("");
                this.passwordtxt.setText("");
            }   } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }//GEN-LAST:event_signinlblMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Forgotpassword forgotpassword=new Forgotpassword();
        forgotpassword.show();
        this.hide();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nationalidtxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JLabel signinlbl;
    private javax.swing.JLabel signuplbl;
    // End of variables declaration//GEN-END:variables
}
